//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnEstadisticaInferencial.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=carnesDB.mssql.somee.com;Integrated Security=False;User ID=keylorsk8_" +
            "SQLLogin_1;Password=k88r6uger9;Connect Timeout=15;Encrypt=False;TrustServerCerti" +
            "ficate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False")]
        public string CarnesDB {
            get {
                return ((string)(this["CarnesDB"]));
            }
            set {
                this["CarnesDB"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=carnesDB.mssql.somee.com;Initial Catalog=carnesDB;Persist Security In" +
            "fo=True;User ID=keylorsk8_SQLLogin_1;Password=k88r6uger9")]
        public string carnesDBConnectionString {
            get {
                return ((string)(this["carnesDBConnectionString"]));
            }
        }
    }
}
